### ISSUE TITLE
QC: syntax for DB xrefs

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#227]
Putting this at low priority, but it might be worth doing at some point. It seems we will still need to use artemis for a while for some annotations (GO ISO) and community curations which can contain  IDs

The GO DB -xrefs file has some syntax description see
local_id_syntax: ^[0-9]{9}$
which could be used to identify any problem ones and report in the logs (I manually fixed a load of SGD IDs in the "with" field last week where I had typed too many zeros, or truncated the last digit....)

abbreviation: PR
database: Protein Ontology
object: Identifer
synonym: PRO
example_id: PR:000025380
local_id_syntax: ^[0-9]{9}$
generic_url: http://www.proconsortium.org/pro/pro.shtml
url_syntax: http://www.proconsortium.org/cgi-bin/pro/entry_pro?id=PR:[example_id]
url_example: http://www.proconsortium.org/cgi-bin/pro/entry_pro?id=PR:000025380
entity_type: PR:000000001 ! protein

HTML access to list:
http://geneontology.org/doc/GO.xrf_abbs

Original comment by: ValWood

**Comment by ValWood** [comment]
Action here is to check that any IDs we use match the  syntax defined in
GO DB -xrefs file


eg.
abbreviation: PR
cal_id_syntax: ^[0-9]{9}$

this would find *some* malformed IDs  that might have been cut and pasted  incorrectly....
I don't think there will be many so it isn't  high priority, but it is is quick it is a nice QC check to have.

**Comment by ValWood** [comment]
seems to overlap with
https://github.com/pombase/pombase-chado/issues/614
?

**Comment by ValWood** [comment]
is this done? 614 now closed...

**Comment by kimrutherford** [comment]
It's not done.  We're not using the GO xrefs file yet.

**Comment by ValWood** [comment]
http://curation.pombase.org/pombe/view/list/db?model=chado

**Comment by ValWood** [comment]
Is this still pending?

**Comment by ValWood** [comment]
Might be useful to implement this syntax check!

**Comment by kimrutherford** [comment]
As a first step, I'm adding code to check the DB prefixes in annotation "with" values.

In my test run, there are only two prefixes that aren't in the GO xrefs file: "CBS" and "ECOGENE".  Both are used only in the legacy GO file:

```
CBS:TMHMM               legacy_go_annotations_from_contigs.gaf.tsv
ECOGENE:EG13357         legacy_go_annotations_from_contigs.gaf.tsv
```

It looks like "CBS" used to be valid.  The xrefs file has this entry:

```yaml
- database: DTU
  name:  DTU Health Tech Services
  description: Formerly CBS (Center for Biological Sequence Analysis)
  generic_urls:
    - http://www.cbs.dtu.dk/services
  entity_types:
    - type_name: entity
      type_id: BET:0000000
      example_id: CBS:TMHMM
      example_url: http://www.cbs.dtu.dk/services/TMHMM/
```

So "CBS:TMHMM" could probably be "DTU:TMHMM".

I don't know about "ECOGENE:"
